apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: pocketdune
nodes:
- role: control-plane
  extraPortMappings:
    # proxy server
  - containerPort: 31000
    hostPort: 31000
  - containerPort: 31001
    hostPort: 31001
  - containerPort: 31002
    hostPort: 31002
  - containerPort: 31003
    hostPort: 31003
  - containerPort: 31004
    hostPort: 31004
  - containerPort: 31005
    hostPort: 31005