# this runs the reverse proxy used by opmonlib
# https://github.com/DUNE-DAQ/influxopmon#authentication
# it is internally exposed as `http://opmonlib-proxy.monitoring`
# it is externally exposed on port 31006

apiVersion: v1
kind: ConfigMap
metadata:
  name: opmonlib-proxy
  namespace: monitoring
data:
  nginx.conf.tpl: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';
      access_log	/var/log/nginx/access.log main;
      server {
          listen       80;
          server_name  _;
          location / {
            proxy_pass http://influxdb.monitoring:8086;
            proxy_set_header Authorization "Token ${INFLUXDB_ADMIN_USER}:${INFLUXDB_ADMIN_USER_PASSWORD}";
          }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opmonlib-proxy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opmonlib-proxy
  template:
    metadata:
      labels:
        app: opmonlib-proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        command:
        - /bin/bash
        args:
        - -c 
        - envsubst < /etc/nginx.tpl/nginx.conf.tpl > /etc/nginx/nginx.conf && nginx -g 'daemon off;'
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: influxdb-secrets
        volumeMounts:
        - mountPath: /etc/nginx.tpl
          readOnly: true
          name: opmonlib-proxy
        - mountPath: /var/log/nginx
          name: log
      volumes:
      - name: opmonlib-proxy
        configMap:
          name: opmonlib-proxy
          items:
          - key: nginx.conf.tpl
            path: nginx.conf.tpl
      - name: log
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: opmonlib-proxy
  namespace: monitoring
spec:
  type: NodePort
  selector:  
    app: opmonlib-proxy  
  ports:  
  - protocol: TCP  
    port: 80  
    targetPort: 80
    nodePort: 31006