# source: kubectl api-resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-readonly
rules:
- apiGroups:
  - ""
  resources:
  - componentstatuses
  - configmaps
  - endpoints
  - events
  - limitranges
  - namespaces
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  # - secrets
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch

- apiGroups:
  - admissionregistration.k8s.io
  - agent.k8s.elastic.co
  - apiextensions.k8s.io
  - apiregistration.k8s.io
  - apm.k8s.elastic.co
  - apps
  - autoscaling
  - batch
  - beat.k8s.elastic.co
  - certificates.k8s.io
  - coordination.k8s.io
  - discovery.k8s.io
  - elasticsearch.k8s.elastic.co
  - enterprisesearch.k8s.elastic.co
  - events.k8s.io
  - extensions
  - flowcontrol.apiserver.k8s.io
  - kibana.k8s.elastic.co
  - maps.k8s.elastic.co
  - networking.k8s.io
  - node.k8s.io
  - policy
  - rbac.authorization.k8s.io
  - scheduling.k8s.io
  - storage.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
