apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-server
spec:
  selector:
    matchLabels:
      app: proxy-server
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy-server
    spec:
      containers:
      - name: proxy-server
        image: serjs/go-socks5-proxy
        ports:
        - containerPort: 1080
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-server
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 1080
    nodePort: 31000
  selector:
    app: proxy-server