name: Test setup.local

on: push

jobs:
  test-local-setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          TARGET: x86_64-unknown-linux-musl
    steps:
    - uses: actions/checkout@v1
    - name: verify docker is functional
      run: docker ps
    - run: make setup.local
    - name: InfluxDB works
      run: |
        kubectl -n monitoring wait --for condition=available deployment influxdb
        curl --fail http://localhost:31002/health | grep "ready for queries and writes"